/**
* @File Name : AnimalResult.cls
* @Description :
* @Author : Mamadou Lamine CAMARA
* @Last Modified By :
* @Last Modified On : March 23, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | March 23, 2025 | Mamadou Lamine CAMARA  | Initial Version
**/

public class AnimalResult {
  public Animal animal;
}