/**
* @File Name : Animal.cls
* @Description :
* @Author : Mamadou Lamine CAMARA
* @Last Modified By :
* @Last Modified On : March 23, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | March 23, 2025 | Mamadou Lamine CAMARA  | Initial Version
**/

public class Animal {
  public Integer id;
  public String name;
  public String eats;
  public String says;
 }